# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Scene(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, number: int=None, name: str=None):  # noqa: E501
        """Scene - a model defined in Swagger

        :param number: The number of this Scene.  # noqa: E501
        :type number: int
        :param name: The name of this Scene.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'number': int,
            'name': str
        }

        self.attribute_map = {
            'number': 'number',
            'name': 'name'
        }
        self._number = number
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'Scene':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Scene of this Scene.  # noqa: E501
        :rtype: Scene
        """
        return util.deserialize_model(dikt, cls)

    @property
    def number(self) -> int:
        """Gets the number of this Scene.

        scene number if available  # noqa: E501

        :return: The number of this Scene.
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number: int):
        """Sets the number of this Scene.

        scene number if available  # noqa: E501

        :param number: The number of this Scene.
        :type number: int
        """

        self._number = number

    @property
    def name(self) -> str:
        """Gets the name of this Scene.

        scene name if available  # noqa: E501

        :return: The name of this Scene.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Scene.

        scene name if available  # noqa: E501

        :param name: The name of this Scene.
        :type name: str
        """

        self._name = name
