# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.quote import Quote  # noqa: F401,E501
from swagger_server import util


class TopsInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, quote: Quote=None):  # noqa: E501
        """TopsInner - a model defined in Swagger

        :param quote: The quote of this TopsInner.  # noqa: E501
        :type quote: Quote
        """
        self.swagger_types = {
            'quote': Quote
        }

        self.attribute_map = {
            'quote': 'quote'
        }
        self._quote = quote

    @classmethod
    def from_dict(cls, dikt) -> 'TopsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Tops_inner of this TopsInner.  # noqa: E501
        :rtype: TopsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def quote(self) -> Quote:
        """Gets the quote of this TopsInner.


        :return: The quote of this TopsInner.
        :rtype: Quote
        """
        return self._quote

    @quote.setter
    def quote(self, quote: Quote):
        """Sets the quote of this TopsInner.


        :param quote: The quote of this TopsInner.
        :type quote: Quote
        """

        self._quote = quote
